services:
  db:
    image: mariadb:11.7.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "Pa55w0rd!"
      MARIADB_DATABASE: nmsdb
    ports:
      - 3306:3306

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/bitnami/redis/data
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080