"""game_id as unique field for Product and Substance

Revision ID: 45453a58023b
Revises: 5755d6365b4d
Create Date: 2025-04-14 07:55:14.860863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45453a58023b'
down_revision: Union[str, None] = '5755d6365b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='product')
    op.create_unique_constraint(None, 'product', ['game_id'])
    op.drop_index('name', table_name='substance')
    op.create_unique_constraint(None, 'substance', ['game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'substance', type_='unique')
    op.create_index('name', 'substance', ['name'], unique=True)
    op.drop_constraint(None, 'product', type_='unique')
    op.create_index('name', 'product', ['name'], unique=True)
    # ### end Alembic commands ###
