"""Set substance name as unique

Revision ID: ee9c6b0f6e07
Revises: 29590a3c67aa
Create Date: 2025-04-13 02:09:56.690494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee9c6b0f6e07'
down_revision: Union[str, None] = '29590a3c67aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'substance', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'substance', type_='unique')
    # ### end Alembic commands ###
